export default Object.freeze({
  THIN: `thin`,
  HAIRLINE: `hairline`,
  EXTRA_LIGHT: `extra-light`,
  ULTRA_LIGHT: `ultra-light`,
  LIGHT: `light`,
  BOOK: `book`,
  NORMAL: `normal`,
  REGULAR: `regular`,
  ROMAN: `roman`,
  MEDIUM: `medium`,
  SEMI_BOLD: `semi-bold`,
  DEMI_BOLD: `demi-bold`,
  BOLD: `bold`,
  EXTRA_BOLD: `extra-bold`,
  ULTRA_BOLD: `ultra-bold`,
  BLACK: `black`,
  HEAVY: `heavy`,
})
